[options]
# see all available configs:
# - https://github.com/odoo/docker/blob/master/18.0/odoo.conf
# - https://gist.github.com/Guidoom/d5db0a76ce669b139271a528a8a2a27f
addons_path = /mnt/extra-addons,/mnt/vendor-addons
data_dir = /var/lib/odoo
log_level = debug
logfile = /var/log/odoo/odoo.log
admin_passwd = odoo
# SMTP server can be set also in Settings > General Settings > Use Custom Email Servers
smtp_server = mail1.run.sk
smtp_user = smtp@example.com
smtp_password = someSecretPassword
smtp_ssl = True
smtp_port = 587
email_from = False
# set access to DB for case of `odoo` command use
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

# custom configs
# _my_custom_config = 'my_value'